# Ignore Failures Scenario

![Generic badge](https://img.shields.io/badge/1/6-FAILED-red.svg)
<details>
  <summary>Duration: 3.904 seconds</summary>
  <table>
    <tr>
      <th>Start:</th>
      <td><code>2024-02-23 20:44:35.369 UTC</code></td>
    </tr>
    <tr>
      <th>Finish:</th>
      <td><code>2024-02-23 20:44:39.273 UTC</code></td>
    </tr>
    <tr>
      <th>Duration:</th>
      <td><code>3.904 seconds</code></td>
    </tr>
  </table>
</details>
<details>
  <summary>Outcome: Failed | Total Tests: 6 | Passed: 5 | Failed: 1</summary>
  <table>
    <tr>
      <th>Total Test Suites:</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Total Tests:</th>
      <td>6</td>
    </tr>
    <tr>
      <th>Failed Test Suites:</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Failed Tests:</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Passed Test Suites:</th>
      <td>0</td>
    </tr>
    <tr>
      <th>Passed Tests:</th>
      <td>5</td>
    </tr>
  </table>
</details>
<details>
  <summary>:x: should be able to open the additional reasons drawer and select a reason</summary>
  <table>
    <tr>
      <th>Title:</th>
      <td><code>should be able to open the additional reasons drawer and select a reason</code></td>
    </tr>
    <tr>
      <th>Status:</th>
      <td><code>failed</code></td>
    </tr>
    <tr>
      <th>Location:</th>
      <td><code>null</code></td>
    </tr>
    <tr>
      <th>Failure Messages:</th>
      <td><pre>Error: expect(jest.fn()).toHaveBeenCalledTimes(expected)

Expected number of calls: 3
Received number of calls: 1
    at toHaveBeenCalledTimes (C:\code\Selector.test.js:69:20)
    at call (C:\code\Selector.test.js:2:1)
    at Generator.tryCatch (C:\code\Selector.test.js:2:1)
    at Generator._invoke [as next] (C:\code\Selector.test.js:2:1)
    at asyncGeneratorStep (C:\code\Selector.test.js:2:1)
    at asyncGeneratorStep (C:\code\Selector.test.js:2:1)</pre></td>
    </tr>
  </table>
</details>
